server:
  port: 8083

spring:
  application:
    name: publication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lokesh
    username: postgres
    password: Gowtham@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.textmachinelab.publication: DEBUG