server:
  port: 8084

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lokesh
    username: postgres
    password: Gowtham@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway

logging:
  level:
    com.textmachinelab.event: DEBUG
    org.flywaydb: DEBUG

# File upload configuration
app:
  upload:
    dir: ./uploads/event-service