version: '3.8'

services:
  # PostgreSQL databases for each microservice
  postgres-users:
    image: postgres:15
    container_name: textlab-users-db
    environment:
      POSTGRES_DB: textlab_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gowtham@123
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  postgres-projects:
    image: postgres:15
    container_name: textlab-projects-db
    environment:
      POSTGRES_DB: textlab_projects
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gowtham@123
    ports:
      - "5434:5432"
    volumes:
      - projects_data:/var/lib/postgresql/data

  postgres-publications:
    image: postgres:15
    container_name: textlab-publications-db
    environment:
      POSTGRES_DB: textlab_publications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gowtham@123
    ports:
      - "5435:5432"
    volumes:
      - publications_data:/var/lib/postgresql/data

  postgres-events:
    image: postgres:15
    container_name: textlab-events-db
    environment:
      POSTGRES_DB: textlab_events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gowtham@123
    ports:
      - "5436:5432"
    volumes:
      - events_data:/var/lib/postgresql/data

  postgres-blogs:
    image: postgres:15
    container_name: textlab-blogs-db
    environment:
      POSTGRES_DB: textlab_blogs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gowtham@123
    ports:
      - "5437:5432"
    volumes:
      - blogs_data:/var/lib/postgresql/data

volumes:
  users_data:
  projects_data:
  publications_data:
  events_data:
  blogs_data: